sudo: false

language: python

python:
  - 3.6

install:
  - pip install coverage
  - pip install pytest
  - pip install -r requirements.txt

script:
  - coverage run --source sixquant -m py.test

after_success:
  - codecov
